services:
  - type: web
    name: rag-assistant-backend
    runtime: python

    buildCommand: pip install --upgrade pip && pip install -r requirements.txt

    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9

      - key: GROQ_API_KEY
        sync: false

      - key: FRONTEND_URL
        sync: false

      - key: FLASK_DEBUG
        value: "false"

      - key: CHROMA_DIR
        value: "/data/chroma_store"

      - key: UPLOAD_DIR
        value: "/data/uploads"
  